
version: "3.9"
services:
  watcher:
    build: .
    environment:
      GitHub__Token: ${GHCR_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./stacks:/stacks
    deploy:
      mode: replicated
      replicas: 1
