version: "3.8"

services:
  swarm-patrol:
    image: ghcr.io/bisand/swarm-patrol:latest
    environment:
      GHCR_TOKEN: ${GHCR_TOKEN}
      POLL_INTERVAL: ${POLL_INTERVAL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      -
        source: swarm-patrol-env-v1
        target: /app/.env
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
secrets:
  swarm-patrol-env-v1:
    external: true
